install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget.exe restore NHtmlUnit.sln -verbosity detailed
  - ps: gitversion /l console /output buildserver

build:
  project: NHtmlUnit.sln

configuration:
  - Release

test:
  assemblies:
    - 'tests/**/bin/*/*Tests.dll'

after_build:
  - ps: |
      Write-Host "nuget pack version $env:GitVersion_NuGetVersion"
      nuget.exe pack app/NHtmlUnit/NHtmlUnit.csproj -Verbosity detailed -Symbols -Properties Configuration=Release -Version $env:GitVersion_NuGetVersion

artifacts:
  - path: 'app/**/*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: Rct2fdDCPZdCId+Xelo02OHeWpN2qMkeve07e1bpk8/wVUDO+KESONQOCe/ah9Wu
  on:
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: Rct2fdDCPZdCId+Xelo02OHeWpN2qMkeve07e1bpk8/wVUDO+KESONQOCe/ah9Wu
  on:
    branch: feature/appveyor-build

notifications:
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
