install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget.exe restore NHtmlUnit.sln -verbosity detailed
  - ps: gitversion /l console /output buildserver

build:
  project: NHtmlUnit.sln

test:
  assemblies:
    - 'tests/**/bin/*/*Tests.dll'

deploy:
- provider: NuGet
  api_key:
    secure: Rct2fdDCPZdCId+Xelo02OHeWpN2qMkeve07e1bpk8/wVUDO+KESONQOCe/ah9Wu
  on:
    appveyor_repo_tag: true
