install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget.exe restore NHtmlUnit.sln -verbosity detailed
  - ps: gitversion /l console /output buildserver

build:
  project: NHtmlUnit.sln
  publish_nuget: true

test:
  assemblies:
    - 'tests/**/bin/*/*Tests.dll'

before_deploy:
  - nuget.cmd pack

deploy:
- provider: NuGet
  api_key:
    secure: Rct2fdDCPZdCId+Xelo02OHeWpN2qMkeve07e1bpk8/wVUDO+KESONQOCe/ah9Wu
  on:
    appveyor_repo_tag: true

notifications:
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
